# Generated by Django 5.2.7 on 2026-04-30 12:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="DailyEventSummary",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("summary_date", models.DateField(unique=True)),
                ("total_events", models.BigIntegerField(default=0)),
                ("failed_events", models.BigIntegerField(default=0)),
                ("changed_events", models.BigIntegerField(default=0)),
                ("unique_hosts", models.IntegerField(default=0)),
                ("top_task_actions", models.JSONField(default=dict)),
                ("duration_stats", models.JSONField(default=dict)),
                ("jobs_covered", models.IntegerField(default=0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "db_table": "events_dailyeventsummary",
            },
        ),
        migrations.CreateModel(
            name="JobEvent",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("awx_event_id", models.BigIntegerField(unique=True)),
                ("job_id", models.IntegerField(db_index=True)),
                ("job_created", models.DateTimeField(db_index=True)),
                ("event_type", models.CharField(db_index=True, max_length=100)),
                ("counter", models.PositiveIntegerField(default=0)),
                ("failed", models.BooleanField(db_index=True, default=False)),
                ("changed", models.BooleanField(default=False)),
                ("task_action", models.CharField(blank=True, default="", max_length=1024)),
                ("task", models.CharField(blank=True, default="", max_length=1024)),
                ("role", models.CharField(blank=True, default="", max_length=1024)),
                ("host_name", models.CharField(blank=True, db_index=True, default="", max_length=1024)),
                ("duration", models.DecimalField(blank=True, decimal_places=6, max_digits=20, null=True)),
                ("awx_created", models.DateTimeField(blank=True, db_index=True, null=True)),
                ("collected_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "db_table": "events_jobevent",
                "indexes": [
                    models.Index(fields=["job_id", "job_created"], name="events_jobe_job_id_409d3f_idx"),
                    models.Index(fields=["task_action", "awx_created"], name="events_jobe_task_ac_282623_idx"),
                    models.Index(fields=["failed", "awx_created"], name="events_jobe_failed_2a0bc9_idx"),
                    models.Index(fields=["host_name", "awx_created"], name="events_jobe_host_na_54610b_idx"),
                ],
            },
        ),
    ]
