# Generated by Django 4.2.21 on 2025-10-14 08:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_user_organization'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='team',
            options={'ordering': ['id'], 'permissions': [('member_team', 'Has all roles assigned to this team')]},
        ),
        migrations.AlterField(
            model_name='organization',
            name='extra_field',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
    ]
