# Generated by Django 4.2.21 on 2025-10-15 12:03

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0006_alter_team_options_alter_organization_extra_field"),
    ]

    operations = [
        migrations.CreateModel(
            name="ConfigurationChange",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "setting_key",
                    models.CharField(
                        help_text="The name of the setting that was changed (e.g., 'DEBUG', 'SECRET_KEY')",
                        max_length=255,
                    ),
                ),
                (
                    "old_value",
                    models.TextField(
                        blank=True,
                        help_text="The previous value of the setting (JSON serialized). May be redacted for sensitive settings.",
                        null=True,
                    ),
                ),
                (
                    "new_value",
                    models.TextField(
                        blank=True,
                        help_text="The new value of the setting (JSON serialized). May be redacted for sensitive settings.",
                        null=True,
                    ),
                ),
                ("changed_at", models.DateTimeField(auto_now_add=True, help_text="Timestamp when the change was made")),
                (
                    "source",
                    models.CharField(
                        choices=[
                            ("api", "API Endpoint"),
                            ("management_command", "Management Command"),
                            ("reload", "Configuration Reload"),
                            ("system", "System Process"),
                        ],
                        help_text="The source of the configuration change",
                        max_length=50,
                    ),
                ),
                (
                    "ip_address",
                    models.GenericIPAddressField(
                        blank=True, help_text="IP address of the requester (if available)", null=True
                    ),
                ),
                (
                    "changed_by",
                    models.ForeignKey(
                        blank=True,
                        help_text="The user who made this configuration change. Null if changed via system process.",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="configuration_changes",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-changed_at"],
                "indexes": [
                    models.Index(fields=["setting_key", "-changed_at"], name="core_config_setting_e93242_idx"),
                    models.Index(fields=["changed_by", "-changed_at"], name="core_config_changed_4c1d42_idx"),
                ],
            },
        ),
    ]
