# Generated by Django 4.2.21 on 2025-10-17 08:49

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0007_configurationchange"),
    ]

    operations = [
        migrations.CreateModel(
            name="Setting",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "key",
                    models.CharField(
                        db_index=True, help_text="Setting key name (e.g., 'DEBUG', 'FEATURE_FLAGS')", max_length=255
                    ),
                ),
                ("value", models.TextField(help_text="JSON-serialized setting value")),
                ("version", models.IntegerField(default=1, help_text="Version number (incremented on each change)")),
                (
                    "category",
                    models.CharField(
                        blank=True,
                        help_text="Category for organization (e.g., 'security', 'features', 'performance')",
                        max_length=50,
                    ),
                ),
                (
                    "is_secret",
                    models.BooleanField(default=False, help_text="Whether this setting contains sensitive data"),
                ),
                (
                    "is_encrypted",
                    models.BooleanField(default=False, help_text="Whether the value is encrypted in storage"),
                ),
                (
                    "changed_at",
                    models.DateTimeField(
                        auto_now_add=True, db_index=True, help_text="Timestamp when this version was created"
                    ),
                ),
                (
                    "source",
                    models.CharField(
                        help_text="Source of the change (e.g., 'api', 'management_command', 'system')", max_length=50
                    ),
                ),
                (
                    "ip_address",
                    models.GenericIPAddressField(
                        blank=True, help_text="IP address of the requester (if applicable)", null=True
                    ),
                ),
                (
                    "changed_by",
                    models.ForeignKey(
                        blank=True,
                        help_text="User who made this change (null for system changes)",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="settings_changes",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Dynamic Setting",
                "verbose_name_plural": "Dynamic Settings",
                "ordering": ["-version"],
                "indexes": [
                    models.Index(fields=["key", "-version"], name="core_settin_key_e0bb5c_idx"),
                    models.Index(fields=["changed_at"], name="core_settin_changed_bac331_idx"),
                    models.Index(fields=["category"], name="core_settin_categor_f2092f_idx"),
                ],
                "unique_together": {("key", "version")},
            },
        ),
    ]
