# WARNING: DO NOT EDIT THIS FILE, IT IS MANAGED BY ANSIBLE-SERVICES-FRAMEWORK.
"""# The main settings for metrics_service.

## On this module

1. Default Settings (regular django settings)
2. Dynaconf instrumentation that loads external settings including
[DAB](https://github.com/ansible/django-ansible-base) defaults

## Loading order

1. Project defaults as defined in the first section of this file.
2. DAB defaults.
3. Application defaults.
   - Top level apps/settings.py
   - Each `app/settings.py` in `apps` directory.
4. DAB conditional settings.
   - Loaded based on what is on current INSTALLED_APPS, MIDDLEWARES etc
5. Overrides from standard paths.
   - /etc/ansible-automation-platform/metrics_service/
6. Overrides from environment variables prefixed with METRICS_SERVICE_.
7. Post loading hooks registered on any Python file loaded before.

## Overrides

> [!NOTE]
> To override defaults define variables on each `apps`/app_name/settings.py.
> To override settings on environments use the override path `/etc/...`
> or set environment variables prefixed with `METRICS_SERVICE_`.
> The environment variables can also be used on development environments
> by adding a `.env` file to the root of the project or creating a
> `settings.local.py`

## Inspecting settings and troubleshooting

To examine the loading history of the settings loading mechanism.

```bash
# Export the Django Settings Module Variable
export DJANGO_SETTINGS_MODULE=metrics_service.settings

# The whole history
uv run dynaconf inspect -m debug -f yaml

# Inspect a variable
uv run dynaconf inspect -k VARIABLE
```

## Default variables
"""

import logging
import os
import sys
from importlib import import_module
from pathlib import Path

from ansible_base.lib.dynamic_config import (
    export,
    factory,
    load_dab_settings,
    load_envvars,
    load_standard_settings_files,
)
from dynaconf.loaders import execute_instance_hooks

BASE_DIR = Path(__file__).resolve().parent.parent
"""Build paths inside the project like this: BASE_DIR / 'subdir'"""

SECRET_KEY = "django-insecure-k^a&fnx3ulh*d2nl%q680o+xkr^5o+c$5=lzo7vd-7=#qmadg("  # noqa
"""SECURITY WARNING: keep the secret key used in production secret!"""

DEBUG = False
"""SECURITY WARNING: don't run with debug turned on in production!"""

ALLOWED_HOSTS = ["*"]
"""List of allowed hosts"""

INSTALLED_APPS = [
    "django.contrib.admin",
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "django.contrib.staticfiles",
    "rest_framework",
]
"""List of installed apps"""

MIDDLEWARE = [
    "django.middleware.security.SecurityMiddleware",
    "whitenoise.middleware.WhiteNoiseMiddleware",
    "django.contrib.sessions.middleware.SessionMiddleware",
    "django.middleware.common.CommonMiddleware",
    "django.middleware.csrf.CsrfViewMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "django.contrib.messages.middleware.MessageMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
    # DAB middlewares
    "crum.CurrentRequestUserMiddleware",
    "ansible_base.lib.middleware.logging.LogRequestMiddleware",
    "ansible_base.lib.middleware.logging.LogTracebackMiddleware",
]
"""List of middleware classes"""


ROOT_URLCONF = "metrics_service.urls"
"""URL configuration for platform_service_example project."""


TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        "DIRS": [
            "apps/core/templates",
            "apps/dynamic_settings/templates",
            "apps/tasks/templates",
            "apps/dashboard/templates",
        ],
        "APP_DIRS": True,
        "OPTIONS": {
            "context_processors": [
                "django.template.context_processors.request",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
            ],
        },
    },
]
"""List of template configurations"""


WSGI_APPLICATION = "metrics_service.wsgi.application"
"""WSGI application configuration"""
ASGI_APPLICATION = "metrics_service.asgi.application"
"""ASGI application configuration"""

DATABASES = {
    "default": {
        "ENGINE": "django.db.backends.sqlite3",
        "NAME": BASE_DIR / "db.sqlite3",
    }
}
"""Database configuration"""

AUTH_PASSWORD_VALIDATORS = [
    {
        "NAME": "django.contrib.auth.password_validation.UserAttributeSimilarityValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.MinimumLengthValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.CommonPasswordValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.NumericPasswordValidator",
    },
]
"""Password validation configuration"""

# Authentication Backends
AUTHENTICATION_BACKENDS = [
    "django.contrib.auth.backends.ModelBackend",  # Default Django auth
]

# Session Configuration
SESSION_ENGINE = "django.contrib.sessions.backends.db"

# Security Settings
SECURE_BROWSER_XSS_FILTER = True
SECURE_CONTENT_TYPE_NOSNIFF = True
X_FRAME_OPTIONS = "DENY"

LOG_LEVEL = os.environ.get("METRICS_SERVICE_LOG_LEVEL", "INFO").upper()
LOGGING = {
    "version": 1,
    "disable_existing_loggers": False,
    "filters": {
        "request_id": {
            "()": "ansible_base.lib.logging.filters.RequestIdFilter",
        },
    },
    "formatters": {
        "simple": {
            "format": "{asctime} {levelname:<8} {name} {message}",
            "style": "{",
        },
        "verbose": {
            "format": "{asctime} {levelname:<8} [{request_id}] {name} {message}",
            "style": "{",
        },
    },
    "handlers": {
        "console": {
            "class": "logging.StreamHandler",
            "formatter": "verbose",
            "filters": ["request_id"],
        },
    },
    "loggers": {
        "ansible_base": {
            "handlers": ["console"],
            "level": LOG_LEVEL,
            "propagate": False,
        },
        "metrics_service": {
            "handlers": ["console"],
            "level": LOG_LEVEL,
            "propagate": False,
        },
        "django": {
            "handlers": ["console"],
            "level": LOG_LEVEL,
            "propagate": False,
        },
        "apps": {
            "handlers": ["console"],
            "level": "INFO",
            "propagate": False,
        },
        "": {
            "handlers": ["console"],
            "level": LOG_LEVEL,
            "propagate": True,
        },
    },
}

LANGUAGE_CODE = "en-us"
"""Language code for this installation."""

TIME_ZONE = "UTC"
"""Time zone for this installation."""

USE_I18N = True
"""Internationalization configuration"""

USE_TZ = True
"""Time zone configuration"""

STATIC_URL = "static/"
"""Static files configuration"""

STATIC_ROOT = BASE_DIR / "staticfiles"
"""Root directory for static files"""

# Only include project-level static dir if it exists (avoids staticfiles.W004 when absent)
STATICFILES_DIRS = [d for d in [BASE_DIR / "static"] if d.exists()]
"""Directories to search for static files"""

MEDIA_URL = "media/"
"""Media files URL endpoint"""

MEDIA_ROOT = BASE_DIR / "media"
"""Root directory for media files"""

DEFAULT_AUTO_FIELD = "django.db.models.BigAutoField"
"""Default primary key field type"""

IS_RUNNING_TESTS = "test" in sys.argv or "PYTEST_VERSION" in os.environ
"""Determine if application is running a testing session."""

LOADED_APPS = []
"""List of apps loaded by the Ansible Services Framework dynamically set at runtime."""

DASHBOARD_COLLECTION = {
    "COLLECTION_SCHEDULE_CRON": "0 */6 * * *",
}
"""Dashboard collection settings.
Override cron via METRICS_SERVICE_DASHBOARD_COLLECTION__COLLECTION_SCHEDULE_CRON env var."""

default_variables = {k: v for k, v in locals().items() if k.isupper()}
"""Variables from this module locals that will be passed to Dynaconf"""

## --- End Default Settings | Start Dynaconf instrumentation --- #

app_prefix = "METRICS_SERVICE"
"""Application prefix for environment variables filtering."""

# Environment: METRICS_SERVICE_MODE, or PRODUCTION=1/true/yes → production (DEBUG=False).
# Do not fall back to ENV; it is too generic and often set by runtimes/CI to values like "test"/"ci".
_mode = os.environ.get("METRICS_SERVICE_MODE") or (
    "production" if os.environ.get("PRODUCTION", "").lower() in ("1", "true", "yes") else None
)
os.environ.setdefault("METRICS_SERVICE_MODE", _mode or "development")
environment = (os.environ.get("METRICS_SERVICE_MODE") or "development").lower()
"""The current environment, by default development"""

DYNACONF = factory(__name__, app_prefix, add_dab_settings=False, **default_variables)
"""Dynaconf instance that comes with settings injected by DAB"""

apps_dir = Path(BASE_DIR / "apps")
"""The directory where the django apps will be discovered from"""

apps_settings_dir = apps_dir / "settings"
"""The directory where the django apps will be discovered from"""

# Load top level apps default settings if exists
if (apps_settings := Path(apps_settings_dir / "defaults.py")).exists():
    DYNACONF.load_file(apps_settings, run_hooks=False)

# Developers can enable new apps via envvars and it must load before envvar loading
if dev_installed_apps := os.getenv("DEV_INSTALLED_APPS", ""):
    if not dev_installed_apps.startswith("@"):
        dev_installed_apps = f"@merge_unique {dev_installed_apps}"
    DYNACONF.set("INSTALLED_APPS", dev_installed_apps)

# Load each app settings in the order defined on INSTALLED_APPS
if apps_dir.exists():
    all_apps = [
        app
        for app in DYNACONF.INSTALLED_APPS
        if app.startswith("apps.") and Path(apps_dir / app.removeprefix("apps.").replace(".", "/")).exists()
    ]
    for app in all_apps:
        DYNACONF.load_file(f"{app}.settings", run_hooks=False)
    DYNACONF.set("LOADED_APPS", all_apps)

# Load environment specific default overrides after all apps/ settings.
if (env_settings := Path(apps_settings_dir / f"{environment}.py")).exists():
    DYNACONF.load_file(env_settings, run_hooks=False)

# load local dev settings if exists
if (dev_file := Path(BASE_DIR / "settings.local.py")).exists():
    DYNACONF.load_file(dev_file)

# DAB default and DAB conditionals that needs to load after project and app settings.
load_dab_settings(DYNACONF)

# Load settings overrides from the standard paths, this is the **user** settings.
load_standard_settings_files(DYNACONF)

# Load envvars at the end to allow them to override everything loaded so far.
load_envvars(DYNACONF)


# SEGMENT_WRITE_KEY from a single file (e.g. installed at build from pipeline secret).
# Default path: /etc/ansible-automation-platform/metrics/segment-write-key.
# Pipeline passes build secret metrics-service-segment-write-keys (SEGMENT_WRITE_KEY_DEV for
# PR/devel, SEGMENT_WRITE_KEY_PROD for GA); one key is installed into that path.
# File content is the raw plaintext key (no encoding).
def _read_segment_key_from_path(path: Path) -> str | None:
    """Read SEGMENT_WRITE_KEY from a single file. Returns the key or None."""
    logger = logging.getLogger(__name__)
    try:
        if not path.is_file():
            return None
        key = path.read_text().strip()
        return key if key else None
    except OSError as e:
        filename = getattr(e, "filename", path)
        logger.error(
            "Failed to read segment write key from %s: %s",
            filename,
            e,
            exc_info=True,
        )
        return None


def _load_segment_write_key_from_file(
    path: Path | None = None,
    dynaconf_instance=None,
) -> None:
    """Load SEGMENT_WRITE_KEY from file and set on Dynaconf. Used at module load and in tests."""
    if path is None:
        _segment_write_key_path = os.environ.get(
            "METRICS_SERVICE_SEGMENT_WRITE_KEY_FILE",
            "/etc/ansible-automation-platform/metrics/segment-write-key",
        )
        path = Path(_segment_write_key_path)
    if dynaconf_instance is None:
        dynaconf_instance = DYNACONF
    # Respect env/settings precedence: do not overwrite if already set
    if os.environ.get("METRICS_SERVICE_SEGMENT_WRITE_KEY", "").strip():
        return
    if dynaconf_instance.get("SEGMENT_WRITE_KEY"):
        return
    if not path.exists():
        return
    key = _read_segment_key_from_path(path)
    if key:
        dynaconf_instance.set("SEGMENT_WRITE_KEY", key)


_load_segment_write_key_from_file()

# ALLOWED_HOSTS from environment: comma-separated list or JSON array
if os.environ.get("METRICS_SERVICE_ALLOWED_HOSTS"):
    import json
    import logging

    raw = os.environ["METRICS_SERVICE_ALLOWED_HOSTS"].strip()
    if raw.startswith("["):
        try:
            parsed = json.loads(raw)
        except (json.JSONDecodeError, TypeError) as e:
            logging.getLogger(__name__).warning(
                "METRICS_SERVICE_ALLOWED_HOSTS: invalid JSON (%s), using empty list: %s",
                type(e).__name__,
                e,
            )
            parsed = []
        if not isinstance(parsed, list):
            logging.getLogger(__name__).warning(
                "METRICS_SERVICE_ALLOWED_HOSTS: expected JSON array, got %s, using empty list",
                type(parsed).__name__,
            )
            parsed = []
        allowed_hosts = [str(x).strip() for x in parsed if str(x).strip()]
        DYNACONF.set("ALLOWED_HOSTS", allowed_hosts)
    else:
        allowed_hosts = [str(x).strip() for x in raw.split(",") if x.strip()]
        DYNACONF.set("ALLOWED_HOSTS", allowed_hosts)

# Container-friendly logging: JSON to stdout when production or METRICS_SERVICE_LOG_FORMAT=json
if environment == "production" or os.environ.get("METRICS_SERVICE_LOG_FORMAT", "").lower() == "json":
    import copy

    log_cfg = copy.deepcopy(DYNACONF.get("LOGGING") or {})
    log_cfg.setdefault("formatters", {})["json"] = {"()": "apps.core.logging_config.JsonFormatter"}
    for h in log_cfg.get("handlers", {}).values():
        if isinstance(h, dict) and "StreamHandler" in str(h.get("class", "")):
            h["formatter"] = "json"
    DYNACONF.set("LOGGING", log_cfg)

# Load development only apps
if not DYNACONF.get("IS_RUNNING_TESTS") and DYNACONF.get("DEBUG"):
    try:
        import debug_toolbar  # noqa
    except ImportError:
        pass  # Ignore if debug_toolbar is not installed
    else:
        DYNACONF.set("INSTALLED_APPS", "@merge_unique debug_toolbar")
        DYNACONF.set("MIDDLEWARE", "@merge_unique debug_toolbar.middleware.DebugToolbarMiddleware")
        DYNACONF.set("DEBUG_TOOLBAR_CONFIG", {"SHOW_TOOLBAR_CALLBACK": lambda request: True})

# This executes the hooks deferred from application settings to execute later.
# TODO(rochacbruno): Move this internally to DAB as a helper method.
execute_instance_hooks(
    DYNACONF,  # type: ignore
    "post",
    [
        _hook
        for _hook in DYNACONF._post_hooks
        if getattr(_hook, "_dynaconf_hook", False) is True and not getattr(_hook, "_called", False)
    ],
)

# Load settings validators from environment-specific file (e.g., production.py, development.py)
if (env_settings := Path(apps_settings_dir / f"{environment}.py")).exists():
    env_module = import_module(f"apps.settings.{environment}")
    if hasattr(env_module, "validators"):
        DYNACONF.validators.register(*env_module.validators)

# Normalize DATABASES OPTIONS: move PostgreSQL session parameters into the psycopg2 'options' string.
# This allows installers to set e.g. METRICS_SERVICE_DATABASES__awx__OPTIONS__datestyle=iso, mdy
# without needing to know the psycopg2-specific OPTIONS__options=-c datestyle=... syntax.
_PG_SESSION_PARAMS = {"datestyle", "search_path", "timezone", "application_name"}
_databases = DYNACONF.get("DATABASES", {})
for _db_conf in _databases.values():
    _opts = _db_conf.get("OPTIONS", {})
    _session_params = {k: _opts.pop(k) for k in list(_opts) if k.lower() in _PG_SESSION_PARAMS}
    if _session_params:
        _existing = _opts.get("options", "")
        _new = " ".join(f"-c {k}={v.replace(' ', '')}" for k, v in _session_params.items())
        _opts["options"] = f"{_existing} {_new}".strip()
DYNACONF.set("DATABASES", _databases)

# Update django.conf.settings with DYNACONF keys.
export(__name__, DYNACONF, validation=False)

## --- End Settings | After this line only post validation can happen --- #
