# Generated by Django 5.2.7 on 2026-01-29 17:35
# Modified to use existing table from tasks app (no database changes needed)

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('tasks', '0002_dashboardreportcache'),  # Ensure tasks migration that created the table runs first
    ]

    operations = [
        # Use SeparateDatabaseAndState to update Django's migration state
        # without modifying the database (table already exists from tasks app)
        migrations.SeparateDatabaseAndState(
            database_operations=[
                # No database operations - table already exists
            ],
            state_operations=[
                # Only update Django's migration state
                migrations.CreateModel(
                    name='DashboardReportCache',
                    fields=[
                        ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                        ('modified', models.DateTimeField(auto_now=True, help_text='The date/time this resource was created.')),
                        ('created', models.DateTimeField(auto_now_add=True, help_text='The date/time this resource was created.')),
                        ('cache_key', models.CharField(db_index=True, help_text="Unique key: '{report_type}_{start_date}_{end_date}'", max_length=255, unique=True)),
                        ('report_type', models.CharField(choices=[('job_templates', 'Job Templates'), ('top_projects', 'Top Projects'), ('top_users', 'Top Users')], db_index=True, help_text='Type of report data cached', max_length=50)),
                        ('data', models.JSONField(help_text='Cached report data in JSON format (matches automation-reports interface)')),
                        ('date_range_start', models.DateTimeField(db_index=True, help_text='Start of data collection period (inclusive)')),
                        ('date_range_end', models.DateTimeField(db_index=True, help_text='End of data collection period (exclusive)')),
                        ('created_by', models.ForeignKey(default=None, editable=False, help_text='The user who created this resource.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_created+', to=settings.AUTH_USER_MODEL)),
                        ('modified_by', models.ForeignKey(default=None, editable=False, help_text='The user who last modified this resource.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_modified+', to=settings.AUTH_USER_MODEL)),
                    ],
                    options={
                        'verbose_name': 'Dashboard Report Cache',
                        'verbose_name_plural': 'Dashboard Report Caches',
                        'db_table': 'dashboard_report_cache',
                        'ordering': ['-modified'],
                        'indexes': [models.Index(fields=['report_type', 'modified'], name='dashboard_r_report_idx'), models.Index(fields=['cache_key', 'modified'], name='dashboard_r_cache_idx')],
                    },
                ),
            ],
        ),
    ]
