# Generated by Django 5.2.7 on 2026-01-30 15:09

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard_reports', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Currency',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('modified', models.DateTimeField(auto_now=True, help_text='The date/time this resource was created.')),
                ('created', models.DateTimeField(auto_now_add=True, help_text='The date/time this resource was created.')),
                ('name', models.CharField(help_text="Full currency name (e.g., 'US Dollar', 'Euro')", max_length=100, unique=True)),
                ('symbol', models.CharField(help_text="Currency symbol (e.g., '$', '€', '£')", max_length=10)),
                ('code', models.CharField(db_index=True, help_text="ISO 4217 currency code (e.g., 'USD', 'EUR', 'GBP')", max_length=3, unique=True)),
                ('is_active', models.BooleanField(default=True, help_text='Whether this currency is available for selection')),
                ('created_by', models.ForeignKey(default=None, editable=False, help_text='The user who created this resource.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_created+', to=settings.AUTH_USER_MODEL)),
                ('modified_by', models.ForeignKey(default=None, editable=False, help_text='The user who last modified this resource.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_modified+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Currency',
                'verbose_name_plural': 'Currencies',
                'db_table': 'dashboard_currency',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='FilterSet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('modified', models.DateTimeField(auto_now=True, help_text='The date/time this resource was created.')),
                ('created', models.DateTimeField(auto_now_add=True, help_text='The date/time this resource was created.')),
                ('name', models.CharField(help_text='Display name for this saved filter set', max_length=255)),
                ('filters', models.JSONField(help_text='Filter configuration: {organizations: [], projects: [], labels: [], date_range: {}}')),
                ('is_default', models.BooleanField(default=False, help_text="Whether this is the user's default filter set (only one allowed per user)")),
                ('created_by', models.ForeignKey(default=None, editable=False, help_text='The user who created this resource.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_created+', to=settings.AUTH_USER_MODEL)),
                ('modified_by', models.ForeignKey(default=None, editable=False, help_text='The user who last modified this resource.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_modified+', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(help_text='User who created this filter set', on_delete=django.db.models.deletion.CASCADE, related_name='filter_sets', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Filter Set',
                'verbose_name_plural': 'Filter Sets',
                'db_table': 'dashboard_filter_set',
                'ordering': ['-modified'],
                'indexes': [models.Index(fields=['user', 'is_default'], name='dashboard_fs_user_default_idx'), models.Index(fields=['user', '-modified'], name='dashboard_fs_user_mod_idx')],
                'constraints': [models.UniqueConstraint(condition=models.Q(('is_default', True)), fields=('user', 'is_default'), name='one_default_per_user', violation_error_message='User can only have one default filter set')],
            },
        ),
        migrations.CreateModel(
            name='TemplateMetadata',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('modified', models.DateTimeField(auto_now=True, help_text='The date/time this resource was created.')),
                ('created', models.DateTimeField(auto_now_add=True, help_text='The date/time this resource was created.')),
                ('template_id', models.IntegerField(db_index=True, help_text='AWX job template ID (from AWX database main_jobtemplate table)', unique=True)),
                ('template_name', models.CharField(help_text='Cached template name for display (from AWX)', max_length=512)),
                ('time_taken_manually_execute_minutes', models.IntegerField(blank=True, help_text='User override: Estimated time to perform this task manually (minutes)', null=True)),
                ('time_taken_create_automation_minutes', models.IntegerField(blank=True, help_text='User override: Estimated time spent creating this automation (minutes)', null=True)),
                ('custom_cost_per_minute', models.DecimalField(blank=True, decimal_places=2, help_text='User override: Custom cost per minute for this specific template', max_digits=10, null=True)),
                ('notes', models.TextField(blank=True, help_text='User notes about this template')),
                ('created_by', models.ForeignKey(default=None, editable=False, help_text='The user who created this resource.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_created+', to=settings.AUTH_USER_MODEL)),
                ('modified_by', models.ForeignKey(default=None, editable=False, help_text='The user who last modified this resource.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_modified+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Template Metadata',
                'verbose_name_plural': 'Template Metadata',
                'db_table': 'dashboard_template_metadata',
                'ordering': ['template_name'],
                'indexes': [models.Index(fields=['template_id'], name='dashboard_tm_template_idx')],
            },
        ),
        migrations.CreateModel(
            name='UserPreference',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('modified', models.DateTimeField(auto_now=True, help_text='The date/time this resource was created.')),
                ('created', models.DateTimeField(auto_now_add=True, help_text='The date/time this resource was created.')),
                ('preferences_data', models.JSONField(blank=True, default=dict, help_text='Additional user preferences (extensible JSON structure)')),
                ('created_by', models.ForeignKey(default=None, editable=False, help_text='The user who created this resource.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_created+', to=settings.AUTH_USER_MODEL)),
                ('currency', models.ForeignKey(blank=True, help_text="User's preferred currency for cost display", null=True, on_delete=django.db.models.deletion.SET_NULL, to='dashboard_reports.currency')),
                ('modified_by', models.ForeignKey(default=None, editable=False, help_text='The user who last modified this resource.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_modified+', to=settings.AUTH_USER_MODEL)),
                ('user', models.OneToOneField(help_text='User who owns these preferences', on_delete=django.db.models.deletion.CASCADE, related_name='dashboard_preferences', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'User Preference',
                'verbose_name_plural': 'User Preferences',
                'db_table': 'dashboard_user_preference',
                'indexes': [models.Index(fields=['user'], name='dashboard_up_user_idx')],
            },
        ),
    ]
