# Generated by Django 5.2.7 on 2026-06-20 07:28

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("dashboard_reports", "0002_jobdata_organization_name"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="DashboardTelemetry",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("modified", models.DateTimeField(auto_now=True, help_text="The date/time this resource was created.")),
                (
                    "created",
                    models.DateTimeField(auto_now_add=True, help_text="The date/time this resource was created."),
                ),
                (
                    "task_name",
                    models.CharField(
                        blank=True,
                        help_text="Name of the task that produced this telemetry entry",
                        max_length=512,
                        null=True,
                    ),
                ),
                ("collection_run_date", models.DateField(help_text="UTC date on which the task ran")),
                ("success", models.BooleanField(default=True, help_text="Whether the task completed without an error")),
                (
                    "collection_duration_ms",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="Collection duration (ms)",
                        max_digits=15,
                        validators=[django.core.validators.MinValueValidator(Decimal("0.00"))],
                    ),
                ),
                (
                    "number_of_records_processed",
                    models.IntegerField(
                        help_text="Number of records processed",
                        validators=[django.core.validators.MinValueValidator(0)],
                    ),
                ),
                (
                    "database_query_time_ms",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="Database query time (ms)",
                        max_digits=15,
                        null=True,
                        validators=[django.core.validators.MinValueValidator(Decimal("0.00"))],
                    ),
                ),
                (
                    "cache_hit_rate",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="Cache hit rate",
                        max_digits=15,
                        null=True,
                        validators=[django.core.validators.MinValueValidator(Decimal("0.00"))],
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        default=None,
                        editable=False,
                        help_text="The user who created this resource.",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(app_label)s_%(class)s_created+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "modified_by",
                    models.ForeignKey(
                        default=None,
                        editable=False,
                        help_text="The user who last modified this resource.",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(app_label)s_%(class)s_modified+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Dashboard Telemetry",
                "verbose_name_plural": "Dashboard Telemetry Entries",
                "db_table": "dashboard_telemetry",
                "indexes": [models.Index(fields=["collection_run_date", "task_name"], name="dash_tel_run_task_idx")],
            },
        ),
    ]
