# Generated by Django 5.2.7 on 2026-01-30 15:09

from django.db import migrations


def initialize_default_currencies(apps, schema_editor):
    """Initialize default currency options for the dashboard."""
    Currency = apps.get_model('dashboard_reports', 'Currency')

    default_currencies = [
        {'name': 'US Dollar', 'symbol': '$', 'code': 'USD'},
        {'name': 'Euro', 'symbol': '€', 'code': 'EUR'},
        {'name': 'British Pound', 'symbol': '£', 'code': 'GBP'},
        {'name': 'Japanese Yen', 'symbol': '¥', 'code': 'JPY'},
        {'name': 'Canadian Dollar', 'symbol': 'C$', 'code': 'CAD'},
        {'name': 'Australian Dollar', 'symbol': 'A$', 'code': 'AUD'},
        {'name': 'Swiss Franc', 'symbol': 'CHF', 'code': 'CHF'},
        {'name': 'Chinese Yuan', 'symbol': '¥', 'code': 'CNY'},
        {'name': 'Indian Rupee', 'symbol': '₹', 'code': 'INR'},
        {'name': 'Brazilian Real', 'symbol': 'R$', 'code': 'BRL'},
    ]

    for currency_data in default_currencies:
        Currency.objects.get_or_create(
            code=currency_data['code'],
            defaults={
                'name': currency_data['name'],
                'symbol': currency_data['symbol'],
                'is_active': True
            }
        )


def reverse_initialize_currencies(apps, schema_editor):
    """Reverse migration: delete initialized currencies."""
    Currency = apps.get_model('dashboard_reports', 'Currency')

    # Only delete currencies we created in this migration
    currency_codes = ['USD', 'EUR', 'GBP', 'JPY', 'CAD', 'AUD', 'CHF', 'CNY', 'INR', 'BRL']
    Currency.objects.filter(code__in=currency_codes).delete()


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard_reports', '0002_currency_filterset_templatemetadata_userpreference'),
    ]

    operations = [
        migrations.RunPython(
            initialize_default_currencies,
            reverse_code=reverse_initialize_currencies
        ),
    ]
