# Generated by Django 5.2.7 on 2026-01-30 15:09

from django.db import migrations


def initialize_dashboard_settings(apps, schema_editor):
    """Initialize global dashboard settings in dynamic_settings table."""
    Setting = apps.get_model('dynamic_settings', 'Setting')

    dashboard_settings = [
        {
            'setting_key': 'automated_process_cost_per_minute',
            'current_value': '0.50',
            'description': 'Cost per minute for automated processes (used in dashboard cost calculations)'
        },
        {
            'setting_key': 'manual_cost_automation_per_hour',
            'current_value': '50.00',
            'description': 'Hourly cost for manual execution of tasks (used in dashboard ROI calculations)'
        },
        {
            'setting_key': 'enable_template_creation_time',
            'current_value': 'true',
            'description': 'Whether to include template creation time in cost calculations'
        },
        {
            'setting_key': 'max_pdf_job_templates',
            'current_value': '100',
            'description': 'Maximum number of job templates to include in PDF exports (prevents memory issues)'
        },
    ]

    for setting_data in dashboard_settings:
        Setting.objects.get_or_create(
            setting_key=setting_data['setting_key'],
            defaults={
                'current_value': setting_data['current_value'],
                'previous_value': ''
            }
        )


def reverse_dashboard_settings(apps, schema_editor):
    """Reverse migration: delete dashboard settings."""
    Setting = apps.get_model('dynamic_settings', 'Setting')

    setting_keys = [
        'automated_process_cost_per_minute',
        'manual_cost_automation_per_hour',
        'enable_template_creation_time',
        'max_pdf_job_templates',
    ]

    Setting.objects.filter(setting_key__in=setting_keys).delete()


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard_reports', '0003_initialize_currencies'),
        ('dynamic_settings', '__latest__'),  # Ensure dynamic_settings table exists
    ]

    operations = [
        migrations.RunPython(
            initialize_dashboard_settings,
            reverse_code=reverse_dashboard_settings
        ),
    ]
