"""
Core models for metrics_service.
For full AAP/DAB features, install with: pip install -e ".[dev]"
"""

# Import DAB components - DAB is always available in this environment

from ansible_base.activitystream.models import AuditableModel
from ansible_base.lib.abstract_models import AbstractDABUser, AbstractOrganization, AbstractTeam, CommonModel
from ansible_base.lib.utils.models import user_summary_fields
from ansible_base.resource_registry.fields import AnsibleResourceField

# Password handling functions from DAB
from django.contrib.auth.hashers import (
    UNUSABLE_PASSWORD_PREFIX,
    UNUSABLE_PASSWORD_SUFFIX_LENGTH,
    get_hashers_by_algorithm,
    identify_hasher,
    make_password,
)
from django.db import models

from .mixins import AccessControlMixin, UserRelatedMixin


def password_is_hashed(password):
    """
    Returns a boolean of whether password is hashed with loaded algorithms.
    """
    if password is None:
        return False
    try:
        hasher = identify_hasher(password)
    except ValueError:
        # hasher can't be identified or is not loaded
        return False
    return hasher.algorithm in get_hashers_by_algorithm()


def password_is_usable(password):
    """
    Returns True if password is None or wasn't generated by django.contrib.auth.hashers.make_password(None).
    """
    unusable_password_len = len(UNUSABLE_PASSWORD_PREFIX) + UNUSABLE_PASSWORD_SUFFIX_LENGTH

    return password is None or not (
        password.startswith(UNUSABLE_PASSWORD_PREFIX) and len(password) == unusable_password_len
    )


class Organization(AbstractOrganization, AccessControlMixin, UserRelatedMixin):
    """
    Organization model with user and admin management capabilities.

    This model represents an organization that can contain users and admins.
    It inherits from AbstractOrganization for DAB compatibility and includes
    access control functionality through AccessControlMixin.
    """

    class Meta:
        ordering = ["id"]
        permissions = [
            ("member_organization", "User is member of this organization"),
        ]

    resource = AnsibleResourceField(primary_key_field="id")

    # UserRelatedMixin provides users and admins fields
    # Override to customize related_name for organizations
    users = models.ManyToManyField(
        "User",
        related_name="member_of_organizations",
        blank=True,
        help_text="The list of users on this organization",
    )

    admins = models.ManyToManyField(
        "User",
        related_name="admin_of_organizations",
        blank=True,
        help_text="The list of admins for this organization",
    )

    # Example custom field - replace or remove as needed
    extra_field = models.CharField(max_length=100, blank=True, default="")

    @classmethod
    def access_qs(cls, user, queryset=None):
        """
        Return queryset filtered by user permissions.
        Includes system auditor logic for read-only access to all organizations.
        """
        if queryset is None:
            queryset = cls.objects.all()

        # System administrators can see everything
        if user.is_superuser:
            return queryset

        # System auditors can see all organizations (read-only)
        if hasattr(user, "is_system_auditor") and getattr(user, "is_system_auditor", False):
            return queryset

        # Regular users: filter by organization membership
        # Only show organizations where user is a member or admin
        user_orgs = queryset.filter(models.Q(users=user) | models.Q(admins=user)).distinct()

        return user_orgs

    def __str__(self):
        """
        Return string representation of the organization.

        Returns:
            str: Organization name
        """
        return self.name


class User(AbstractDABUser, CommonModel, AuditableModel, AccessControlMixin):
    """
    Custom User model with enhanced functionality.

    This model extends the AbstractDABUser with additional functionality
    including access control and proper password handling.
    """

    class Meta(AbstractDABUser.Meta):
        ordering = ["id"]

    # Override the groups and user_permissions to avoid conflicts with auth.User
    groups = models.ManyToManyField(
        "auth.Group",
        verbose_name="groups",
        blank=True,
        help_text="The groups this user belongs to.",
        related_name="core_user_set",
        related_query_name="core_user",
    )
    user_permissions = models.ManyToManyField(
        "auth.Permission",
        verbose_name="user permissions",
        blank=True,
        help_text="Specific permissions for this user.",
        related_name="core_user_set",
        related_query_name="core_user",
    )

    # System auditor flag
    is_system_auditor = models.BooleanField(
        default=False, help_text="Designates that this user has read-only access to all resources."
    )
    organization = models.ForeignKey(
        Organization,
        on_delete=models.CASCADE,
        null=True,
        blank=True,
        help_text="The organization this user belongs to.",
    )

    resource = AnsibleResourceField(primary_key_field="id")
    activity_stream_excluded_field_names = ["last_login", "password"]

    def save(self, *args, **kwargs):
        """
        Override save to handle password hashing and organization membership.
        """
        # Store the old organization if this is an update
        old_organization = None
        if self.pk:
            try:
                old_user = User.objects.get(pk=self.pk)
                old_organization = old_user.organization
            except User.DoesNotExist:
                pass

        if self.password == "":
            self.password = None

        if password_is_usable(self.password) and not password_is_hashed(self.password):
            self.password = make_password(self.password)

        super().save(*args, **kwargs)

        # Handle organization membership after save
        self._handle_organization_membership(old_organization)

    def _handle_organization_membership(self, old_organization):
        """
        Automatically manage organization membership when user's organization changes.
        """
        # Remove from old organization if it changed
        if old_organization and old_organization != self.organization:
            old_organization.users.remove(self)

        # Add to new organization if one is assigned
        if self.organization and not self.organization.users.filter(id=self.id).exists():
            self.organization.users.add(self)
        # Add user to the organization's users if not already there

    def summary_fields(self):
        """
        Return summary fields for this user.

        Returns:
            dict: Summary fields dictionary
        """
        return user_summary_fields(self)

    @classmethod
    def access_qs(cls, user, queryset=None):
        """
        Return queryset filtered by user permissions.
        Includes system auditor logic for read-only access to all users.
        """
        if queryset is None:
            queryset = cls.objects.all()

        # System administrators can see all users
        if user.is_superuser:
            return queryset

        # System auditors can see all users (read-only)
        if hasattr(user, "is_system_auditor_user") and user.is_system_auditor_user():
            return queryset

        # Regular users: filter by organization relationships
        # Show users in same organizations or teams
        user_organizations = user.member_of_organizations.all()
        user_teams = user.teams.all()

        accessible_users = queryset.filter(
            models.Q(id=user.id)  # Always include self
            | models.Q(member_of_organizations__in=user_organizations)  # Same org members
            | models.Q(teams__in=user_teams)  # Same team members
        ).distinct()

        return accessible_users

    def is_system_administrator(self):
        """
        Check if user has system administrator privileges.
        System administrators have full access to all resources.
        """
        return self.is_superuser

    def is_system_auditor_user(self):
        """
        Check if user has system auditor privileges (read-only access).
        System auditors can view all resources but cannot modify them.
        """
        return self.is_system_auditor

    def can_manage_organization(self, organization):
        """Check if user can manage a specific organization."""
        return self.is_system_administrator() or organization.admins.filter(id=self.id).exists()

    def can_view_organization(self, organization):
        """Check if user can view a specific organization."""
        return (
            self.is_system_administrator()
            or self.is_system_auditor_user()
            or organization.users.filter(id=self.id).exists()
            or organization.admins.filter(id=self.id).exists()
        )

    def can_manage_team(self, team):
        """Check if user can manage a specific team."""
        return (
            self.is_system_administrator()
            or team.admins.filter(id=self.id).exists()
            or self.can_manage_organization(team.organization)
        )

    def __str__(self):
        """
        Return string representation of the user.

        Returns:
            str: Username
        """
        return self.username


class Team(AbstractTeam, AccessControlMixin, UserRelatedMixin):
    """
    Team model with hierarchical organization support.

    This model represents a team within an organization that can contain
    users and admins, with support for team hierarchies.
    """

    class Meta:
        ordering = ["id"]
        abstract = False
        unique_together = [("organization", "name")]
        permissions = [("member_team", "Has all roles assigned to this team")]

    resource = AnsibleResourceField(primary_key_field="id")

    team_parents = models.ManyToManyField(
        "Team",
        related_name="team_children",
        blank=True,
        help_text="Parent teams for hierarchy support",
    )

    # Override UserRelatedMixin fields to use proper User model and related_name
    users = models.ManyToManyField(
        User,
        related_name="teams",
        blank=True,
        help_text="The list of users on this team",
    )

    admins = models.ManyToManyField(
        User,
        related_name="teams_administered",
        blank=True,
        help_text="The list of admins for this team",
    )

    # Relations to ignore for certain operations
    ignore_relations = []

    @classmethod
    def access_qs(cls, user, queryset=None):
        """
        Return queryset filtered by user permissions.
        Includes system auditor logic for read-only access to all teams.
        """
        if queryset is None:
            queryset = cls.objects.all()

        # System administrators can see all teams
        if user.is_superuser:
            return queryset

        # System auditors can see all teams (read-only)
        if hasattr(user, "is_system_auditor_user") and user.is_system_auditor_user():
            return queryset

        # Regular users: filter by organization and team membership
        user_organizations = user.member_of_organizations.all()

        accessible_teams = queryset.filter(
            models.Q(organization__in=user_organizations)  # Teams in user's orgs
            | models.Q(users=user)  # Teams user is member of
            | models.Q(admins=user)  # Teams user administers
        ).distinct()

        return accessible_teams

    def __str__(self):
        """
        Return string representation of the team.

        Returns:
            str: Organization name and team name
        """
        return f"{self.organization.name} - {self.name}"


class SettingManager(models.Manager):
    """Custom manager for Setting model with transaction locking and cache updates."""

    def create_or_update(
        self,
        key: str,
        value: str,
        user: "User | None" = None,
        source: str = "api",
        ip_address: str | None = None,
        category: str = "",
        is_secret: bool = False,
    ) -> "Setting":
        """
        Create new version of a setting with proper locking and cache management.

        Args:
            key: Setting key name
            value: JSON-serialized setting value
            user: User making the change
            source: Source of the change ('api', 'management_command', etc.)
            ip_address: IP address of requester
            category: Setting category for organization
            is_secret: Whether this setting contains sensitive data

        Returns:
            Setting: The newly created setting version
        """
        import json
        import logging

        from django.core.cache import cache
        from django.db import transaction

        logger = logging.getLogger(__name__)

        # Validate the setting value
        try:
            self._validate_setting(key, value)
        except Exception as e:
            logger.error(f"Validation failed for {key}: {e}")
            raise

        # Use database transaction with row-level locking (select_for_update)
        with transaction.atomic():
            # Lock the latest version of this key for update (prevents concurrent modifications)
            latest = self.filter(key=key).select_for_update().order_by("-version").first()
            new_version = (latest.version + 1) if latest else 1

            # Create new version
            setting = self.create(
                key=key,
                value=value,
                version=new_version,
                changed_by=user,
                source=source,
                ip_address=ip_address,
                category=category,
                is_secret=is_secret,
            )

            # Update cache
            cache_key = f"setting:{key}"
            cache.set(cache_key, value, timeout=None)

            logger.info(f"Setting {key} updated to version {new_version} by {user or 'system'}")

            return setting

    def _validate_setting(self, key: str, value: str) -> None:
        """
        Validate a setting value using Dynaconf validators.

        Args:
            key: Setting key
            value: JSON-serialized value

        Raises:
            ValueError: If validation fails
        """
        import json

        from dynaconf import ValidationError, Validator

        # Ensure value is valid JSON
        try:
            json.loads(value)
        except json.JSONDecodeError as e:
            raise ValueError(f"Invalid JSON value for {key}: {e}") from e

        # Additional validation can be added here
        # For now, we trust that the value is valid


class Setting(models.Model):
    """
    Database-backed key-value storage for dynamic preferences (Phase 2).

    This model implements ADR 0014 Phase 2 specifications for runtime
    configuration management. Each setting change creates a new immutable
    version, allowing for complete audit trail and rollback capability.

    Features:
    - Versioned: Each change creates new version, previous versions kept
    - Immutable: Records cannot be modified after creation
    - Audited: Tracks who, what, when, where for all changes
    - Cached: Automatically syncs to Redis cache for fast access
    - Validated: Values validated before storage

    Usage:
        # Create or update a setting
        Setting.objects.create_or_update(
            key='DEBUG',
            value='false',
            user=request.user,
            source='api'
        )

        # Get latest version
        setting = Setting.get_latest('DEBUG')
    """

    # What
    key = models.CharField(
        max_length=255,
        db_index=True,
        help_text="Setting key name (e.g., 'DEBUG', 'FEATURE_FLAGS')",
    )
    value = models.TextField(
        help_text="JSON-serialized setting value",
    )
    version = models.IntegerField(
        default=1,
        help_text="Version number (incremented on each change)",
    )

    # Metadata
    category = models.CharField(
        max_length=50,
        blank=True,
        help_text="Category for organization (e.g., 'security', 'features', 'performance')",
    )
    is_secret = models.BooleanField(
        default=False,
        help_text="Whether this setting contains sensitive data",
    )
    is_encrypted = models.BooleanField(
        default=False,
        help_text="Whether the value is encrypted in storage",
    )

    # Auditing - WHO changed it
    changed_by = models.ForeignKey(
        User,
        on_delete=models.SET_NULL,
        null=True,
        blank=True,
        related_name="settings_changes",
        help_text="User who made this change (null for system changes)",
    )

    # Auditing - WHEN it changed
    changed_at = models.DateTimeField(
        auto_now_add=True,
        db_index=True,
        help_text="Timestamp when this version was created",
    )

    # Auditing - WHERE it came from
    source = models.CharField(
        max_length=50,
        help_text="Source of the change (e.g., 'api', 'management_command', 'system')",
    )
    ip_address = models.GenericIPAddressField(
        null=True,
        blank=True,
        help_text="IP address of the requester (if applicable)",
    )

    # Custom manager
    objects = SettingManager()

    class Meta:
        unique_together = [["key", "version"]]
        ordering = ["-version"]  # Newest first
        indexes = [
            models.Index(fields=["key", "-version"]),  # Fast lookup of latest version
            models.Index(fields=["changed_at"]),  # Fast lookup by time
            models.Index(fields=["category"]),  # Fast lookup by category
        ]
        verbose_name = "Dynamic Setting"
        verbose_name_plural = "Dynamic Settings"

    def __str__(self) -> str:
        """String representation showing key and version."""
        return f"{self.key} (v{self.version})"

    @classmethod
    def get_latest(cls, key: str) -> "Setting | None":
        """
        Get the latest version of a setting.

        Args:
            key: Setting key name

        Returns:
            Setting instance or None if not found
        """
        return cls.objects.filter(key=key).order_by("-version").first()

    @classmethod
    def get_version(cls, key: str, version: int) -> "Setting | None":
        """
        Get a specific version of a setting.

        Args:
            key: Setting key name
            version: Version number

        Returns:
            Setting instance or None if not found
        """
        return cls.objects.filter(key=key, version=version).first()

    @classmethod
    def get_history(cls, key: str) -> models.QuerySet:
        """
        Get all versions of a setting ordered by version (newest first).

        Args:
            key: Setting key name

        Returns:
            QuerySet of Setting instances
        """
        return cls.objects.filter(key=key).order_by("-version")


class ConfigurationChange(models.Model):
    """
    DEPRECATED: Legacy model for tracking configuration changes.

    This model is kept for backward compatibility. New code should use
    the Setting model which provides versioning and dynamic preferences.

    This model serves as an audit log for all configuration changes, recording who changed what, when, and from where.
    """

    # WHO changed it
    changed_by = models.ForeignKey(
        User,
        on_delete=models.SET_NULL,
        null=True,
        blank=True,
        related_name="configuration_changes",
        help_text="The user who made this configuration change. Null if changed via system process.",
    )

    # WHAT was changed
    setting_key = models.CharField(
        max_length=255,
        help_text="The name of the setting that was changed (e.g., 'DEBUG', 'SECRET_KEY')",
    )

    old_value = models.TextField(
        blank=True,
        null=True,
        help_text="The previous value of the setting (JSON serialized). May be redacted for sensitive settings.",
    )

    new_value = models.TextField(
        blank=True,
        null=True,
        help_text="The new value of the setting (JSON serialized). May be redacted for sensitive settings.",
    )

    # WHEN it changed
    changed_at = models.DateTimeField(
        auto_now_add=True,
        help_text="Timestamp when the change was made",
    )

    # WHERE it came from
    source = models.CharField(
        max_length=50,
        choices=[
            ("api", "API Endpoint"),
            ("management_command", "Management Command"),
            ("reload", "Configuration Reload"),
            ("system", "System Process"),
        ],
        help_text="The source of the configuration change",
    )

    # Extra info
    ip_address = models.GenericIPAddressField(
        null=True,
        blank=True,
        help_text="IP address of the requester (if available)",
    )

    class Meta:
        ordering = ["-changed_at"]  # Show newest changes first
        indexes = [
            models.Index(fields=["setting_key", "-changed_at"]),  # Fast lookup by setting
            models.Index(fields=["changed_by", "-changed_at"]),  # Fast lookup by user
        ]

    def __str__(self):
        """String representation showing who changed what and when."""
        user_name = self.changed_by.username if self.changed_by else "System"
        return f"{user_name} changed {self.setting_key} at {self.changed_at}"
